Update

diff --git a/run_onchange_after_install-packages.sh.tmpl b/run_onchange_after_install-packages.sh.tmpl
--- a/run_onchange_after_install-packages.sh.tmpl
+++ b/run_onchange_after_install-packages.sh.tmpl
@@ -1,38 +1,51 @@
 #!/bin/sh
 
-if [ ! -f /etc/pacman.d/chaotic-mirrorlist ]; then
-  # Import the chaotic-aur signing key
-  sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
-  sudo pacman-key --lsign-key 3056513887B78AEB
-
-  # Install the chaotic-aur keyring and mirrorlist
-  sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
-  sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
-
-  # Add the chaotic-aur repository to /etc/pacman.conf if not already added
-  if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
-    sudo sh -c 'echo "
-  [chaotic-aur]
-  Include = /etc/pacman.d/chaotic-mirrorlist
-  " >> /etc/pacman.conf'
-    echo "chaotic-aur repository added to /etc/pacman.conf."
-  else
-    echo "chaotic-aur repository already exists in /etc/pacman.conf."
-  fi
-fi
-
-# Update the package database
-sudo pacman -Sy
-
 # Function to check if a package is installed
 is_installed() {
-  yay -Q "$1" > /dev/null 2>&1
+  pacman -Q "$1" > /dev/null 2>&1
 }
 
 # Function to check if a package is available in chaotic-aur
 is_in_chaotic_aur() {
-  yay -Sl chaotic-aur | grep " $1 "
+  echo "$chaotic_aur_list" | grep -q " $1 "
 }
+
+# Check if we can modify the pacman keyring
+if sudo pacman-key --init > /dev/null 2>&1; then
+  echo "Have necessary permissions to modify pacman keyring."
+
+  # Check if /etc/pacman.d/chaotic-mirrorlist exists
+  if [ ! -f /etc/pacman.d/chaotic-mirrorlist ]; then
+    echo "chaotic-mirrorlist not found, proceeding to install chaotic-aur keyring and mirrorlist."
+
+    # Import the chaotic-aur signing key
+    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
+    sudo pacman-key --lsign-key 3056513887B78AEB
+
+    # Install the chaotic-aur keyring and mirrorlist
+    sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
+    sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
+  else
+    echo "chaotic-mirrorlist already exists."
+  fi
+
+  # Add the chaotic-aur repository to /etc/pacman.conf if not already added
+  if [ -f /etc/pacman.d/chaotic-mirrorlist ] && ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
+    sudo sh -c 'printf "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist\n" >> /etc/pacman.conf'
+
+    echo "chaotic-aur repository added to /etc/pacman.conf."
+  else
+    echo "chaotic-aur repository already exists in /etc/pacman.conf or chaotic-mirrorlist not found."
+  fi
+else
+  echo "Insufficient permissions to modify pacman keyring. Skipping chaotic-aur setup."
+fi
+
+# Update the package database
+sudo pacman -Syu
+
+# Save the list of chaotic-aur packages in a variable
+chaotic_aur_list=$(yay -Sl chaotic-aur)
 
 # List of packages to check and install if necessary
 PACKAGE_LIST="
@@ -69,7 +82,6 @@ mpv-uosc
 neovim
 nomacs
 nvm
-obsidian-bin
 okular
 peek
 pistol-git
@@ -78,7 +90,6 @@ ripgrep
 shellcheck-bin
 solaar
 speedcrunch
-syncthing
 tdrop
 tealdeer
 tmux
@@ -101,11 +112,13 @@ flacon
 fsearch-git
 librewolf-bin
 mullvad-vpn-bin
+obsidian-bin
 puddletag-git
 rsgain
 signal-desktop
 soundconverter
 sox
+syncthing
 thunderbird
 transmission-remote-gtk
 whatsdesk-bin
@@ -120,14 +133,34 @@ echo "$PACKAGE_LIST" | while IFS= read -r package_name; do
     if is_installed "$package_name"; then
       echo "$package_name ✔"
     else
-
       if is_in_chaotic_aur "$package_name"; then
-        echo "Installing chaotic-aur/$package_name ..."
-        yay -S --noconfirm "chaotic-aur/$package_name"
+        echo "Installing $package_name from chaotic-aur ..."
+        sudo pacman -S --noconfirm "chaotic-aur/$package_name"
       else
         echo "Installing $package_name ..."
-        yay -S --noconfirm "$package_name"
+        sudo pacman -S --noconfirm "$package_name"
       fi
     fi
   fi
 done
+
+# Define the file path to the chezmoi configuration file
+chezmoi_config="$HOME/.config/chezmoi/chezmoi.toml"
+
+# Define the git settings to be added
+chezmoi_git_settings='
+[git]
+    autoCommit = true
+    autoPush = true
+    commitMessageTemplate = "Update"
+'
+
+# Check if the git settings already exist in the chezmoi configuration file
+if ! grep -q '\[git\]' "$chezmoi_config"; then
+  # If the settings do not exist, append them to the configuration file
+  printf "%s\n" "$chezmoi_git_settings" >> "$chezmoi_config"
+
+  echo "Git settings added to $chezmoi_config."
+else
+  echo "Git settings already exist in $chezmoi_config."
+fi
